import { Item } from "./types";

export const items: Item[] = [
  {
    name: "Еда качества 0",
    description: "Сытость, -2 стресса, -1 здоровье (0 медных)",
    category: "Еда",
    price: 0,
    image: "./pripasi_0.jpg",
  },
  {
    name: "Еда качества 1",
    description: "Сытость, -1 стресс (3 медных)",
    category: "Еда",
    price: 3,
    image: "./pripasi_1.jpg",
  },
  {
    name: "Еда качества 2",
    description: "Сытость (5 медных)",
    category: "Еда",
    price: 5,
    image: "./pripasi_2.jpg",
  },
  {
    name: "Еда качества 3",
    description: "Сытость, +1 стресс, +1 здоровье, +1 сытость (10 медных)",
    category: "Еда",
    price: 10,
    image: "./pripasi_3.jpg",
  },
  {
    name: "Еда качества 4",
    description:
      "Сытость, +1 стресс, +1 здоровье, +1 сытость (дважды) (20 медных)",
    category: "Еда",
    price: 20,
    image: "./pripasi_4.jpg",
  },
  {
    name: "Еда качества 5",
    description:
      "Сытость, +1 стресс, +1 здоровье, +1 сытость (трижды) (40 медных)",
    category: "Еда",
    price: 40,
    image: "./pripasi_5.jpg",
  },
  {
    name: "Еда качества 6",
    description:
      "Сытость, +1 стресс, +1 здоровье, +1 сытость (четырежды) (80 медных)",
    category: "Еда",
    price: 80,
    image: "./pripasi_6.jpg",
  },
  {
    name: "Пряности",
    description: "Пол года готовка +4 к броскам",
    category: "Еда",
    price: 500,
  },
  {
    name: "Южные специи",
    description:
      "При готовке с ними бросок с помехой, но +5 к значению +7 если есть кулинария",
    category: "Еда",
    price: 500,
    image: "./specii.jpg",
  },
  {
    name: "Табак плохой",
    description:
      "20 использований (25% - 1 стресс при использовании, 8.3% - 1 здоровье)",
    category: "Табак",
    price: 120,
  },
  {
    name: "Табак обычный",
    description:
      "20 использований (50% - 1 стресс при использовании, 8.3% - 1 здоровье)",
    category: "Табак",
    price: 200,
  },
  {
    name: "Табак отличный",
    description:
      "20 использований (100% - 1 стресс при использовании, 8.3% - 1 здоровье)",
    category: "Табак",
    price: 400,
  },
  {
    name: "Табак крепкий",
    description:
      "20 использований (25% - 2 стресс при использовании, 75% - 1 стресс при использовании, 16.6% - 1 здоровье)",
    category: "Табак",
    price: 500,
  },
  {
    name: "Табак Журавля",
    description:
      "20 использований (100% - 1 стресс при использовании, 33% - блокирует психоз, 66%- блокирует любую ломку, 8.3% - 1 здоровье)",
    category: "Табак",
    price: 550,
  },
  {
    name: "Эль",
    description: "(25% -1 стресс)",
    category: "Алкоголь",
    price: 5,
    image: "./desh_el.png"
  },
  {
    name: "Дешёвое вино",
    description: "(50% - 1 стресс)",
    category: "Алкоголь",
    price: 10,
  },
  {
    name: "Стопка настойки",
    description: "(25% - 2 стресса)",
    category: "Алкоголь",
    price: 10,
  },
  {
    name: "Медовуха",
    description: "(75% - 1 стресс)",
    category: "Алкоголь",
    price: 15,
  },
  {
    name: "Пиво",
    description: "(100% - 1 стресс)",
    category: "Алкоголь",
    price: 20,
  },
  {
    name: "Среднее вино",
    description: "(50% - 2 стресса)",
    category: "Алкоголь",
    price: 20,
  },
  {
    name: "Сидр",
    description: "(50% - 1 стресс, 25% - 2 стресса)",
    category: "Алкоголь",
    price: 20,
  },
  {
    name: "Стопка самогона",
    description: "(33% - 2 стресса)",
    category: "Алкоголь",
    price: 20,
  },
  {
    name: "Дорогой эль",
    description: "(100% - 2 стресса)",
    category: "Алкоголь",
    price: 40,
    image: "./el.png"
  },
  {
    name: "Крепленое вино",
    description: "(50% - 4 стресса)",
    category: "Алкоголь",
    price: 40,
  },
  {
    name: "Виски",
    description: "(50% - 3 стресса, 50% - 1 стресс)",
    category: "Алкоголь",
    price: 40,
    image: "./viski.jpg",
  },
  {
    name: "Ром",
    description: "(66% -2 стресса, 33% - 3 стресса)",
    category: "Алкоголь",
    price: 40,
  },
  {
    name: "Качественная настойка",
    description: "(33%-4 стресса , 33%-2 стресса, 33% - 1 стресс)",
    category: "Алкоголь",
    price: 40,
  },
  {
    name: "Дорогое вино",
    description: "(50% - 4 стресса, 50% - 2 стресса)",
    category: "Алкоголь",
    price: 60,
  },
  {
    name: "Спирт",
    description: "Нужен при лечении, чтобы избежать заражения и гноения",
    category: "Медикаменты",
    price: 25,
  },
  {
    name: "Бинт",
    description: "Нужен для лечения",
    category: "Медикаменты",
    price: 10,
  },
  {
    name: "Опиум",
    description: "Снимает стресс и боль",
    category: "Медикаменты",
    price: 20,
    image: "./opium.jpg",
  },
  {
    name: "Мертвояд",
    description:
      "Временное универсальное, снимает эффекты большинства ядов на время",
    category: "Медикаменты",
    price: 10,
    image: "./mertv.jpg",
  },
  {
    name: "Противоядие",
    description: "",
    category: "Медикаменты",
    price: 20,
  },
  {
    name: "Снотворное",
    description: "Помогает заснуть",
    category: "Медикаменты",
    price: 10,
  },
  {
    name: "Зубной порошок",
    description: "Лечит зубы",
    category: "Медикаменты",
    price: 5,
  },
  {
    name: "Мыло",
    description: "Позволяет сохранять гигиену",
    category: "Медикаменты",
    price: 5,
  },
  {
    name: "Сироп целебный",
    description: "Снимает терапевтически болезни, снижает температуру",
    category: "Медикаменты",
    price: 20,
    image: "./celeb.jpg",
  },
  {
    name: "Микстура целебная",
    description: "Усиленный сироп, но дает + 1 стресс",
    category: "Медикаменты",
    price: 30,
    image: "./mikst.jpg",
  },
  {
    name: "Медицинская игла, нить и скальпель",
    description: "Нужно для лечения",
    category: "Медикаменты",
    price: 30,
  },
  {
    name: "Факел",
    description: "",
    category: "Предметы",
    price: 5,
    image: "./fakel.jpg",
  },
  {
    name: "Масло для костра",
    description: "",
    category: "Предметы",
    price: 10,
    image: "./maslo.jpg",
  },
  {
    name: "Масло Дракона",
    description: "",
    category: "Предметы",
    price: 30,
    image: "./drakona.jpg",
  },
  {
    name: "Болт",
    description: "",
    category: "Предметы",
    price: 1,
    image: "./bolt.jpg",
  },
  {
    name: "Стрела",
    description: "",
    category: "Предметы",
    price: 5,
    image: "./strela.jpg",
  },
  {
    name: "Порох",
    description: "",
    category: "Предметы",
    price: 50,
    image: "./puli.jpg",
  },
  {
    name: "Пули",
    description: "",
    category: "Предметы",
    price: 50,
    image: "./puli.jpg",
  },
  {
    name: "Серебряные пули",
    description: "",
    category: "Предметы",
    price: 200,
  },
  {
    name: "Взрывные пули",
    description: "",
    category: "Предметы",
    price: 200,
  },
  {
    name: "Железо пластина",
    description: "",
    category: "Предметы",
    price: 10,
  },
  {
    name: "Пластина сталь древа",
    description: "",
    category: "Предметы",
    price: 100,
  },
  {
    name: "Дубленая кожа",
    description: "",
    category: "Предметы",
    price: 10,
  },
  {
    name: "Набор для шитья",
    description: "",
    category: "Предметы",
    price: 150,
  },
  {
    name: "Набор для письма",
    description: "",
    category: "Предметы",
    price: 50,
  },
  {
    name: "Тетива",
    description: "",
    category: "Предметы",
    price: 30,
  },
  {
    name: "Шёлковая тетива",
    description: "",
    category: "Предметы",
    price: 50,
  },
  {
    name: "Механизмы",
    description: "",
    category: "Предметы",
    price: 35,
  },
  {
    name: "Сложные механизмы",
    description: "",
    category: "Предметы",
    price: 70,
  },
  {
    name: "Ткань",
    description: "",
    category: "Предметы",
    price: 20,
  },
  {
    name: "Дорогая ткань",
    description: "",
    category: "Предметы",
    price: 50,
  },
  {
    name: "Набор инструментов",
    description: "",
    category: "Предметы",
    price: 100,
  },
  {
    name: "Качественные инструменты",
    description: "",
    category: "Предметы",
    price: 400,
  },
  {
    name: "Элексир",
    description: "",
    category: "Предметы",
    price: 100,
  },
  {
    name: "Краски",
    description: "",
    category: "Предметы",
    price: 200,
  },
  {
    name: "Благовония",
    description: "",
    category: "Предметы",
    price: 400,
  },
  {
    name: "Спальник",
    description: "",
    category: "Предметы",
    price: 250,
  },
  {
    name: "Качественный спальник",
    description: "",
    category: "Предметы",
    price: 500,
    image: "./spal_kach.jpg",
  },
  {
    name: "Утепленный спальник",
    description: "",
    category: "Предметы",
    price: 800,
  },
  {
    name: "Палатка простая одноместная",
    description: "",
    category: "Предметы",
    price: 500,
    image: "./palatka_prost.jpg",
  },
  {
    name: "Палатка качественная",
    description: "",
    category: "Предметы",
    price: 1000,
  },
  {
    name: "Трубка простая",
    description: "",
    category: "Предметы",
    price: 50,
  },
  {
    name: "Трубка хорошая",
    description: "(+1 бросок при курении)",
    category: "Предметы",
    price: 300,
    image: "./trubka_hor.jpg",
  },
  {
    name: "Трубка великолепная",
    description: "(+1 бросок при курении выбирается лучший)",
    category: "Предметы",
    price: 1500,
  },
  {
    name: "Игральные карты",
    description: "",
    category: "Предметы",
    price: 200,
    image: "./karti.jpg",
  },
  {
    name: "Игральные кости",
    description: "",
    category: "Предметы",
    price: 50,
    image: "./kosti.jpg",
  },
  {
    name: "Качественные игральные кости",
    description: "",
    category: "Предметы",
    price: 200,
  },
  {
    name: "Косметика",
    description: "(50 использований)",
    category: "Предметы",
    price: 500,
  },
  {
    name: "Верёвка 15 метров",
    description: "",
    category: "Предметы",
    price: 250,
    image: "./verevka.jpg",
  },
  {
    name: "Посуда",
    description: "",
    category: "Предметы",
    price: 400,
  },
  {
    name: "Фонарь",
    description: "",
    category: "Предметы",
    price: 100,
  },
  {
    name: "Осколки стекла",
    description: "Бесценно",
    category: "Предметы",
    price: 0,
    image: "./oskolki.png",
  },
  {
    name: "Городская одежда",
    description: "",
    category: "Одежда",
    price: 250,
    image: "./gorod.jpg"
  },
  {
    name: "Дорогая одежда",
    description: "",
    category: "Одежда",
    price: 700,
  },
  {
    name: "Великолепная одежда",
    description: "",
    category: "Одежда",
    price: 1200,
    image: "./velek_od.jpg"
  },
  {
    name: "Тёплая одежда",
    description: "",
    category: "Одежда",
    price: 800,
  },
  {
    name: "Крупный плащ",
    description: "",
    category: "Одежда",
    price: 500,
  },
  {
    name: "Простое кольцо",
    description: "Медь/железо/не драгоценные камни",
    category: "Одежда",
    price: 50,
  },
  {
    name: "Хорошее кольцо",
    description: "Серебро",
    category: "Одежда",
    price: 100,
  },
  {
    name: "Отличное кольцо",
    description: "Золото/серебро/драгоценные камни/инкустрировка",
    category: "Одежда",
    price: 500,
  },
  {
    name: "Драгоценное кольцо",
    description: "Золото/крупные драгоценные камни/тонкая работа",
    category: "Одежда",
    price: 1250,
  },
  {
    name: "Ожерелье",
    description: "",
    category: "Одежда",
    price: 200,
  },
  {
    name: "Дорогое ожерелье",
    description: "",
    category: "Одежда",
    price: 1000,
  },
  {
    name: "Драгоценное ожерелье",
    description: "",
    category: "Одежда",
    price: 2500,
  },
  {
    name: "Браслет",
    description: "",
    category: "Одежда",
    price: 100,
  },
  {
    name: "Дорогой браслет",
    description: "",
    category: "Одежда",
    price: 600,
  },
  {
    name: "Драгоценный браслет",
    description: "",
    category: "Одежда",
    price: 1800,
  },
  {
    name: "Серьги",
    description: "",
    category: "Одежда",
    price: 50,
  },
  {
    name: "Хорошие серьги",
    description: "",
    category: "Одежда",
    price: 100,
  },
  {
    name: "Отличные серьги",
    description: "",
    category: "Одежда",
    price: 500,
  },
  {
    name: "Драгоценные серьги",
    description: "",
    category: "Одежда",
    price: 1250,
  },
  {
    name: "Очки",
    description: "",
    category: "Одежда",
    price: 100,
  },
  {
    name: "Кожаная броня",
    description: "(8 брони) (без шума и минусов подвижности)",
    category: "Одежда",
    price: 600,
  },
  {
    name: "Укрепленная кожаная броня",
    description: "(10 брони) (без шума и минусов подвижности)",
    category: "Одежда",
    price: 1200,
  },
  {
    name: "Лёгкая броня",
    description: "(10 брони)",
    category: "Одежда",
    price: 1000,
  },
  {
    name: "Средняя броня",
    description: "(13 брони) - 1 к ловкости",
    category: "Одежда",
    price: 2100,
  },
  {
    name: "Крепкая броня",
    description: "(16 брони) -2 к ловкости",
    category: "Одежда",
    price: 3100,
    image: "./24.png",
  },
  {
    name: "Латная броня",
    description: "(19 брони) - 3 к ловкости",
    category: "Одежда",
    price: 4500,
  },
  {
    name: "Облегчённая Средняя броня",
    description: "(13 брони)",
    category: "Одежда",
    price: 2300,
  },
  {
    name: "Облегчённая крепкая броня",
    description: "(16 брони) -1 к ловкости",
    category: "Одежда",
    price: 3500,
  },
  {
    name: "Качественные походные сумки",
    description: "(фляга, больше веса, выше проворность, удобство)",
    category: "Одежда",
    price: 300,
  },
  {
    name: "Баклер",
    description: "",
    category: "Оружие",
    price: 200,
  },
  {
    name: "Превосходный баклер",
    description: "",
    category: "Оружие",
    price: 700,
    image: "./prev_bak.jpg",
  },
  {
    name: "Кинжал",
    description: "",
    category: "Оружие",
    price: 50,
    image: "./1.png",
  },
  {
    name: "Отличный кинжал",
    description: "",
    category: "Оружие",
    price: 200,
    image: "./2.png",
  },
  {
    name: "Превосходный кинжал",
    description: "",
    category: "Оружие",
    price: 500,
    image: "./3.png",
  },
  {
    name: "Кремневый пистолет",
    description: "",
    category: "Оружие",
    price: 200,
  },
  {
    name: "Длиноствольный кремневый пистолет",
    description: "",
    category: "Оружие",
    price: 400,
  },
  {
    name: "Быстрозарядный пистолет",
    description: "",
    category: "Оружие",
    price: 400,
  },
  {
    name: "Двухзарядный пистолет",
    description: "",
    category: "Оружие",
    price: 800,
  },
  {
    name: "Мушкет",
    description: "",
    category: "Оружие",
    price: 1200,
  },
  {
    name: "Обрез",
    description: "",
    category: "Оружие",
    price: 600,
  },
  {
    name: "Двухстволка",
    description: "",
    category: "Оружие",
    price: 1200,
  },
  {
    name: "Винтовка",
    description: "",
    category: "Оружие",
    price: 2000,
  },
  {
    name: "Лук",
    description: "",
    category: "Оружие",
    price: 100,
    image: "./4.png",
  },
  {
    name: "Короткий степной лук",
    description: "",
    category: "Оружие",
    price: 200,
    image: "./4.png",
  },
  {
    name: "Тисовый лук",
    description: "",
    category: "Оружие",
    price: 200,
  },
  {
    name: "Дворянский лук",
    description: "",
    category: "Оружие",
    price: 500,
  },
  {
    name: "Арбалет",
    description: "",
    category: "Оружие",
    price: 700,
  },
  {
    name: "Ручной арбалет",
    description: "",
    category: "Оружие",
    price: 1000,
  },
  {
    name: "Автоматический арбалет",
    description: "",
    category: "Оружие",
    price: 1300,
  },
  {
    name: "Одноручный топорик",
    description: "",
    category: "Оружие",
    price: 200,
  },
  {
    name: "Короткий меч",
    description: "",
    category: "Оружие",
    price: 400,
  },
  {
    name: "Одноручный меч бастард",
    description: "",
    category: "Оружие",
    price: 700,
  },
  {
    name: "Одноручный качественный меч",
    description: "",
    category: "Оружие",
    price: 1100,
  },
  {
    name: "Одноручный меч из стальдрева",
    description: "",
    category: "Оружие",
    price: 2100,
  },
  {
    name: "Двуручный меч",
    description: "",
    category: "Оружие",
    price: 1400,
  },
  {
    name: "Сбалансированный двуручный меч",
    description: "",
    category: "Оружие",
    price: 2200,
  },
  {
    name: "Двуручный меч из стальдрева",
    description: "",
    category: "Оружие",
    price: 3400,
  },
  {
    name: "Копьё",
    description: "",
    category: "Оружие",
    price: 200,
  },
  {
    name: "Сбалансированное копьё",
    description: "",
    category: "Оружие",
    price: 500,
  },
  {
    name: "Дымовая шашка",
    description: "",
    category: "Боевые предметы",
    price: 50,
  },
  {
    name: "Взрывчатка",
    description: "",
    category: "Боевые предметы",
    price: 50,
  },
  {
    name: "Метательные кинжалы",
    description: "за кинжал",
    category: "Боевые предметы",
    price: 20,
  },
  {
    name: "Метательные топоры",
    description: "за топор",
    category: "Боевые предметы",
    price: 100,
  },
];
